/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wumch_pecar_Interact */

#ifndef _Included_com_wumch_pecar_Interact
#define _Included_com_wumch_pecar_Interact
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wumch_pecar_Interact
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wumch_pecar_Interact_start
  (JNIEnv *, jclass);

/*
 * Class:     com_wumch_pecar_Interact
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wumch_pecar_Interact_stop
  (JNIEnv *, jclass);

/*
 * Class:     com_wumch_pecar_Interact
 * Method:    setConfig
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wumch_pecar_Interact_setConfig
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
